# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env

# Set the working directory
WORKDIR /app

# Copy everything to the working directory
COPY ./Plot ./

# Expose the port on which the app will run
EXPOSE 8080

# Set the entrypoint to run with dotnet watch for hot reload
ENTRYPOINT ["dotnet", "watch", "run", "--non-interactive", "--use-polling-file-watcher"]