name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    steps:
      - name: Checkout DB Repository
        uses: actions/checkout@v4
        with:
          repository: SVSU-Capstone25/PLOT-DB
          path: database

      - name: Docker Build DB
        run: docker build -t plot-db:latest ./database

      - name: Docker Run DB
        run: docker run -d -e DB_NAME='sqlpreview' -e ACCEPT_EULA='Y' -e MSSQL_SA_PASSWORD='yourStrong(!)Password' -p 1433:1433 plot-db:latest

      - name: Checkout BE Repository
        uses: actions/checkout@v4
        with:
          repository: SVSU-Capstone25/PLOT-BE
          path: backend

      - name: Docker Build BE
        run: docker build -t plot-be:latest ./backend

      - name: Docker Run BE
        run: docker run -d -p 8085:8085 plot-be:latest

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Checkout FE Repository
        uses: actions/checkout@v4
        with:
          path: frontend

      - name: Docker Build FE
        run: docker build -t plot-fe:latest ./frontend

      - name: Docker Run FE
        run: docker run -d -p 8080:8080 plot-fe:latest

      - name: Dotnet Build FE
        run: dotnet build ./frontend

      - name: Install Playwright Browsers and Dependencies
        run: |
          pwsh ./frontend/Plot.Tests/bin/Debug/net9.0/playwright.ps1 install --with-deps

      - name: Wait for Services to be Ready
        run: |
          until curl -s http://localhost:8085/health; do
            echo "Waiting for backend..."
            sleep 5
          done

      - name: Test FE
        run: dotnet test ./frontend
