name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4

      - name: Checkout Backend Repository
        uses: actions/checkout@v4
        with:
          repository: SVSU-Capstone25/PLOT-BE
          path: backend

      - name: Checkout Database Repository
        uses: actions/checkout@v4
        with:
          repository: SVSU-Capstone25/PLOT-DB
          path: database

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for Services to be Ready
        run: |
          until curl -s http://localhost:8085/health; do
            echo "Waiting for backend..."
            sleep 5
          done

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npx playwright test
